name: Static analytics 1016
on: 
    pull_request:
        paths: ['.github/workflows/*.yml', '.github/workflows/*.yaml']
defaults:
    run:
        shell: bash # ワークフローで使うシェルをまとめて指定する
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }} # Concurrencyグループへワークフロー名を指定
    cancel-in-progress: true # 同一グループのワークフローが実行中ならキャンセル
jobs:
  actionlint:
    runs-on: ubuntu-latest
    timeout-minutes: 5 # ワークフローのタイムアウトを5分に設定
    steps:
      - uses: actions/checkout@v2
      - run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
  # https://rhysd.hatenablog.com/entry/2021/07/11/214313